package com.whd.model;

public class Image {
    /**
     *
     * This   field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Sun Nov 04 12:22:11 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.img
     *
     * @mbg.generated Sun Nov 04 12:22:11 CST 2018
     */
    private Object img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Sun Nov 04 12:22:11 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Sun Nov 04 12:22:11 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.img
     *
     * @return the value of image.img
     *
     * @mbg.generated Sun Nov 04 12:22:11 CST 2018
     */
    public Object getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.img
     *
     * @param img the value for image.img
     *
     * @mbg.generated Sun Nov 04 12:22:11 CST 2018
     */
    public void setImg(Object img) {
        this.img = img;
    }
}